# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import paintstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopImageExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='../static/images/camera-bg.jpg', null=True, upload_to='headers/', verbose_name='image')),
                ('size', models.CharField(choices=[('short', 'Short'), ('large', 'Large')], default=('short', 'Short'), max_length=16, verbose_name='size')),
                ('color', paintstore.fields.ColorPickerField(default='#1f3549', max_length=7)),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='studiorec.TopImageExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
