# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studiorec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topimageextension',
            name='color',
        ),
    ]
