# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 16:58
from __future__ import unicode_literals

from django.db import migrations
import paintstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studiorec', '0002_remove_topimageextension_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='topimageextension',
            name='color',
            field=paintstore.fields.ColorPickerField(default='#1f3549', max_length=7),
        ),
    ]
